WebProje/Controllers/HayvanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProje.Models;

namespace WebProje.Controllers
{
    [Authorize(Roles = "admin")]
    public class HayvanController : Controller
    {
        HayvanBarinagiContext context = new HayvanBarinagiContext();

        [HttpGet]
        public async Task<IActionResult> Index()
        {
           var hayvan = await context.Hayvan.ToListAsync();
            return View(hayvan);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Hayvanlar hayvan)
        {
            var h = new Hayvanlar()
            {
                HayvanResim = hayvan.HayvanResim,
                HayvanAdi = hayvan.HayvanAdi,
                Tur = hayvan.Tur,
                Sahiplenildimi = false
            };
            await context.Hayvan.AddAsync(h);
            await context.SaveChangesAsync();
            return RedirectToAction("Create");

        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var hayvan = await context.Hayvan.FirstOrDefaultAsync(x => x.Id == id);
            if(hayvan != null)
            {
                var viewModel = new Hayvanlar()
                {
                    HayvanResim = hayvan.HayvanResim,
                    Id = hayvan.Id,
                    HayvanAdi = hayvan.HayvanAdi,
                    Tur = hayvan.Tur,
                    Sahiplenildimi = hayvan.Sahiplenildimi
                };
                return View(viewModel);
            }
            
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit( Hayvanlar model)
        {
            var hayvan = await context.Hayvan.FindAsync(model.Id);
            if(hayvan != null)
            {
                hayvan.HayvanResim = model.HayvanResim;
                hayvan.HayvanAdi = model.HayvanAdi;
                hayvan.Tur = model.Tur;
                hayvan.Sahiplenildimi = model.Sahiplenildimi;
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hayvan = await context.Hayvan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hayvan == null)
            {
                return NotFound();
            }

            return View(hayvan);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Hayvanlar model)
        {
            var hayvan = context.Hayvan.Find(model.Id);
            if(hayvan != null)
            {
                context.Hayvan.Remove(hayvan);
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        

    }
    

}

WebProje/Controllers/SahiplenmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.PowerBI.Api.Models;
using WebProje.Data;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class SahiplenmeController : Controller
    {
        HayvanBarinagiContext context = new HayvanBarinagiContext();
        [Authorize(Roles = "admin,user")]
        [HttpGet]
       public IActionResult Index(int? id)
        {
            ViewData["id"] = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index( Sahiplenme yeni,int id)
        {
            var istek = new Sahiplenme()
            {
                HayvanId = id,
                isim = yeni.isim,
                soyIsim = yeni.soyIsim,
                TC = yeni.TC,
                dogumTarihi = yeni.dogumTarihi,
                adres = yeni.adres,
                soru1 = yeni.soru1,
                soru2 = yeni.soru2,
                soru3 = yeni.soru3,
                soru4=yeni.soru4,
                
            };
            await context.Sahiplenme.AddAsync(istek);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var sahiplenme = await context.Sahiplenme.ToListAsync();
            return View(sahiplenme);
        }
        public async Task<IActionResult> Kabul(int? id)
        {
            var hayvan = await context.Hayvan.FirstOrDefaultAsync(x => x.Id == id );
            hayvan.Sahiplenildimi = true;
            await context.SaveChangesAsync();
            return RedirectToAction("List");
        }
        public async Task<IActionResult> Reddet(int? id)
        {
            var hayvan = await context.Hayvan.FirstOrDefaultAsync(x => x.Id == id);
            var sahip = await context.Sahiplenme.FirstOrDefaultAsync(x => x.HayvanId == id);
            hayvan.Sahiplenildimi = false;
            context.Sahiplenme.Remove(sahip);
            await context.SaveChangesAsync();
            return RedirectToAction("List");
        }
    }
}

WebProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: linear-gradient(rgba(0,0,0,0.75),rgba(0,0,0,0.55)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhB33WazlvBo2nw-f3Our79OUY7peY3oMqow&usqp=CAU);
            background-position: center;
            background-size: cover;
        }   
        
        nav {
            opacity:0.7;
        }
        #dropdownMenuButton {
            height: 40px;
            width: 150px;
            margin-right: 20px;
            text-align:center;
            padding-bottom:10px;
        }
        .dropdown{
            text-align:center;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProje</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Hayvanlar">Hayvanlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sahiplenme" asp-action="Index">Sahiplenme</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hayvan" asp-action="Create">Admin Paneli</a>
                        </li>
                        }
                    </ul>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Diller
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US" >English</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="de-DE">Deutsch</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="nl-NL">Netherland</a>
                        </div>
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>